name: flutter_clean_architecture
description: A Flutter package that implements the Clean Architecture by Uncle Bob in Flutter. It provides Views, Controllers, Presenters, Observers, and UseCases.
version: 5.0.4-dev.0
homepage: https://github.com/laevad/flutter_clean_architecture/

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  meta: ^1.9.1
  provider: ^6.0.5
  responsive_builder: ^0.7.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
